### Using loc and iloc

In [13]:
import pandas as pd 

college = pd.read_csv('D:/python/Pandas/PandasCookbook_Code/data/college.csv',index_col='INSTNM')
city = college['CITY']
city.loc['Enterprise State Community College']

'Enterprise'

In [6]:
city.head(20)

0             Normal
1         Birmingham
2         Montgomery
3         Huntsville
4         Montgomery
5         Tuscaloosa
6     Alexander City
7             Athens
8         Montgomery
9             Auburn
10        Birmingham
11       Phenix City
12             Selma
13        Montgomery
14        Enterprise
15       Bay Minette
16        Montgomery
17           Gadsden
18       Albertville
19            Dothan
Name: CITY, dtype: object

In [15]:
college.head(60)

                                                              CITY STABBR  ...    MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                                                                     ...
Alabama A & M University                                    Normal     AL  ...              30300               33888
University of Alabama at Birmingham                     Birmingham     AL  ...              39700             21941.5
Amridge University                                      Montgomery     AL  ...              40100               23370
University of Alabama in Huntsville                     Huntsville     AL  ...              45500               24097
Alabama State University                                Montgomery     AL  ...              26600             33118.5
The University of Alabama                               Tuscaloosa     AL  ...              41900               23750
Central Alabama Community College                   Alexander City     AL  ...              27500               16127
Athens State University                                     Athens     AL  ...              39000               18595
Auburn University at Montgomery                         Montgomery     AL  ...              35000               21335
Auburn University                                           Auburn     AL  ...              45700               21831
Birmingham Southern College                             Birmingham     AL  ...              44200               27000
Chattahoochee Valley Community College                 Phenix City     AL  ...              26100                9000
Concordia College Alabama                                    Selma     AL  ...              19900   PrivacySuppressed
South University-Montgomery                             Montgomery     AL  ...              28800               25167
Enterprise State Community College                      Enterprise     AL  ...              24600                8273
James H Faulkner State Community College               Bay Minette     AL  ...              28700               11000
Faulkner University                                     Montgomery     AL  ...              37200               22000
Gadsden State Community College                            Gadsden     AL  ...              25700   PrivacySuppressed
New Beginning College of Cosmetology                   Albertville     AL  ...                NaN                5500
George C Wallace State Community College-Dothan             Dothan     AL  ...              26600   PrivacySuppressed
George C Wallace State Community College-Hancev...      Hanceville     AL  ...              28800               11186
George C Wallace State Community College-Selma               Selma     AL  ...              24200   PrivacySuppressed
Herzing University-Birmingham                           Birmingham     AL  ...              42300             23216.5
Huntingdon College                                      Montgomery     AL  ...              36500               26230
Heritage Christian University                             Florence     AL  ...  PrivacySuppressed   PrivacySuppressed
J F Drake State Community and Technical College         Huntsville     AL  ...              22300   PrivacySuppressed
Jacksonville State University                         Jacksonville     AL  ...              34600               23000
Jefferson Davis Community College                          Brewton     AL  ...              25400   PrivacySuppressed
Jefferson State Community College                       Birmingham     AL  ...              29400              8916.5
John C Calhoun State Community College                      Tanner     AL  ...              27400               10500
Judson College                                              Marion     AL  ...              29300   PrivacySuppressed
Lawson State Community College-Birmingham Campus        Birmingham     AL  ...              23800   PrivacySuppressed
University of West Alabama                              Livingston     AL  ...              33900               24253
Lurleen B Wallace Community College                      Andalusia     AL  ...              25200   PrivacySuppressed
Marion Military Institute                                   Marion     AL  ...              44500               11500
Miles College                                            Fairfield     AL  ...              25700             36789.5
University of Mobile                                        Mobile     AL  ...              35000               27000
University of Montevallo                                Montevallo     AL  ...              34900               23266
Northwest-Shoals Community College                   Muscle Shoals     AL  ...              25200               11250
University of North Alabama                               Florence     AL  ...              36100               21500
Northeast Alabama Community College                     Rainsville     AL  ...              28300                4500
Oakwood University                                      Huntsville     AL  ...              33900               27250
Alabama Southern Community College                     Monroeville     AL  ...              22400   PrivacySuppressed
Prince Institute-Southeast                                Elmhurst     IL  ...  PrivacySuppressed               20992
Reid State Technical College                             Evergreen     AL  ...              20100   PrivacySuppressed
Bishop State Community College                              Mobile     AL  ...              21800   PrivacySuppressed
Samford University                                      Birmingham     AL  ...              45800               23000
Selma University                                             Selma     AL  ...                NaN   PrivacySuppressed
Shelton State Community College                         Tuscaloosa     AL  ...              24700   PrivacySuppressed
Snead State Community College                                 Boaz     AL  ...              26500                6374
University of South Alabama                                 Mobile     AL  ...              37300               24711
Spring Hill College                                         Mobile     AL  ...              42800               27000
Southeastern Bible College                              Birmingham     AL  ...              30300               24000
Stillman College                                        Tuscaloosa     AL  ...              25700               38218
Talladega College                                        Talladega     AL  ...              25100               27745
H Councill Trenholm State Community College             Montgomery     AL  ...              23100   PrivacySuppressed
Troy University                                               Troy     AL  ...              35600               25000
Tuskegee University                                       Tuskegee     AL  ...              36800               33500
United States Sports Academy                                Daphne     AL  ...  PrivacySuppressed   PrivacySuppressed
Bevill State Community College                              Jasper     AL  ...              25900   PrivacySuppressed

[60 rows x 26 columns]

In [26]:
college.iloc[58]

CITY                             Daphne
STABBR                               AL
HBCU                                0.0
MENONLY                             0.0
WOMENONLY                           0.0
RELAFFIL                              0
SATVRMID                            NaN
SATMTMID                            NaN
DISTANCEONLY                        0.0
UGDS                               90.0
UGDS_WHITE                       0.4333
UGDS_BLACK                       0.1222
UGDS_HISP                        0.0667
UGDS_ASIAN                       0.0222
UGDS_AIAN                           0.0
UGDS_NHPI                           0.0
UGDS_2MOR                        0.0444
UGDS_NRA                            0.0
UGDS_UNKN                        0.3111
PPTUG_EF                         0.8111
CURROPER                              1
PCTPELL                             0.4
PCTFLOAN                         0.4632
UG25ABV                          0.4737
MD_EARN_WNE_P10       PrivacySuppressed
GRAD_DEBT_MDN_SUPP    PrivacySuppressed
Name: United States Sports Academy, dtype: object

In [27]:
college.iloc[10:20]

                                                        CITY STABBR  HBCU  ...  UG25ABV  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                                                                     ...
Birmingham Southern College                       Birmingham     AL   0.0  ...   0.0152            44200               27000
Chattahoochee Valley Community College           Phenix City     AL   0.0  ...   0.3876            26100                9000
Concordia College Alabama                              Selma     AL   1.0  ...   0.2367            19900   PrivacySuppressed
South University-Montgomery                       Montgomery     AL   0.0  ...   0.5726            28800               25167
Enterprise State Community College                Enterprise     AL   0.0  ...   0.3399            24600                8273
James H Faulkner State Community College         Bay Minette     AL   0.0  ...   0.2909            28700               11000
Faulkner University                               Montgomery     AL   0.0  ...   0.4589            37200               22000
Gadsden State Community College                      Gadsden     AL   1.0  ...   0.3733            25700   PrivacySuppressed
New Beginning College of Cosmetology             Albertville     AL   0.0  ...   0.3933              NaN                5500
George C Wallace State Community College-Dothan       Dothan     AL   0.0  ...   0.3920            26600   PrivacySuppressed

[10 rows x 26 columns]

In [31]:
college.iloc[2:8,0:3]

                                               CITY STABBR  HBCU
INSTNM
Amridge University                       Montgomery     AL   0.0
University of Alabama in Huntsville      Huntsville     AL   0.0
Alabama State University                 Montgomery     AL   1.0
The University of Alabama                Tuscaloosa     AL   0.0
Central Alabama Community College    Alexander City     AL   0.0
Athens State University                      Athens     AL   0.0

In [34]:
college.iloc[:,[2,4]]

                                                    HBCU  WOMENONLY
INSTNM
Alabama A & M University                             1.0        0.0
University of Alabama at Birmingham                  0.0        0.0
Amridge University                                   0.0        0.0
University of Alabama in Huntsville                  0.0        0.0
Alabama State University                             1.0        0.0
...                                                  ...        ...
SAE Institute of Technology  San Francisco           NaN        NaN
Rasmussen College - Overland Park                    NaN        NaN
National Personal Training Institute of Cleveland    NaN        NaN
Bay Area Medical Academy - San Jose Satellite L...   NaN        NaN
Excel Learning Center-San Antonio South              NaN        NaN

[7535 rows x 2 columns]

In [36]:
college.columns

Index(['CITY', 'STABBR', 'HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL',
       'SATVRMID', 'SATMTMID', 'DISTANCEONLY', 'UGDS', 'UGDS_WHITE',
       'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI',
       'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF', 'CURROPER', 'PCTPELL',
       'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10', 'GRAD_DEBT_MDN_SUPP'],
      dtype='object')

In [39]:
college.iloc[5]

CITY                  Tuscaloosa
STABBR                        AL
HBCU                         0.0
MENONLY                      0.0
WOMENONLY                    0.0
RELAFFIL                       0
SATVRMID                   555.0
SATMTMID                   565.0
DISTANCEONLY                 0.0
UGDS                     29851.0
UGDS_WHITE                0.7825
UGDS_BLACK                0.1119
UGDS_HISP                 0.0348
UGDS_ASIAN                0.0106
UGDS_AIAN                 0.0038
UGDS_NHPI                 0.0009
UGDS_2MOR                 0.0261
UGDS_NRA                  0.0268
UGDS_UNKN                 0.0026
PPTUG_EF                  0.0844
CURROPER                       1
PCTPELL                    0.204
PCTFLOAN                   0.401
UG25ABV                   0.0853
MD_EARN_WNE_P10            41900
GRAD_DEBT_MDN_SUPP         23750
Name: The University of Alabama, dtype: object

In [47]:
%timeit college.iloc[:,[4,5]]

433 µs ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [71]:
college['Alabama A & M University':'Alabama State University':2]

                                CITY STABBR  HBCU  MENONLY  ...  PCTFLOAN  UG25ABV  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                                                      ...
Alabama A & M University      Normal     AL   1.0      0.0  ...    0.8284   0.1049            30300               33888
Amridge University        Montgomery     AL   0.0      0.0  ...    0.7795   0.8540            40100               23370
Alabama State University  Montgomery     AL   1.0      0.0  ...    0.7554   0.1270            26600             33118.5

[3 rows x 26 columns]

In [72]:
college.sort_index(inplace=True)

In [79]:
college.loc['D':'E']

                                                    CITY STABBR  HBCU  ...  UG25ABV    MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                                                                 ...
D & L Academy of Hair Design                  Twin Falls     ID   0.0  ...   0.6000                NaN   PrivacySuppressed
D A Dorsey Technical College                       Miami     FL   0.0  ...   0.3696                NaN   PrivacySuppressed
D'Jay's School of Beauty Arts and Sciences   Baton Rouge     LA   0.0  ...   0.4286              15500                7327
D'Mart Institute                            Barranquitas     PR   0.0  ...   0.3523              12900   PrivacySuppressed
D'Youville College                               Buffalo     NY   0.0  ...   0.3099              48000               25500
...                                                  ...    ...   ...  ...      ...                ...                 ...
Durham Beauty Academy                             Durham     NC   0.0  ...   0.4000  PrivacySuppressed               15332
Durham Technical Community College                Durham     NC   0.0  ...   0.5961              27200             11069.5
Dutchess BOCES-Practical Nursing Program    Poughkeepsie     NY   0.0  ...   0.5430              36500                9500
Dutchess Community College                  Poughkeepsie     NY   0.0  ...   0.1806              32500               10250
Dyersburg State Community College              Dyersburg     TN   0.0  ...   0.3097              26800                7475

[224 rows x 26 columns]